### ISSUE TITLE
Enable brave tools to reuse existing lxd bridges

### ISSUE THREAD

**Issue by idroz** [bravetools/bravetools#103]
If a Bridget already exists, brave tools should reuse it - creation of multiple bridges on the same host seems to result in unresolved DNSs in containers...

**Comment by Szubie** [comment]
Perhaps bravetools should go back to using the `bravebr0` name for its bridge if we take this route; if there's only one bravetools bridge by design it is clearer than using the username.

**Comment by idroz** [comment]
Agreed

**Comment by idroz** [comment]
I guess the only caveat LXD has a non-brave bridge already set up. Should we create our own for Bravetools, or just re-use the existing bridge?

Looping in @adrozdovbering for thoughts as well.

**Comment by idroz** [comment]
I was looking into this a bit more - #143 ensures that a bridge gets a unique private RFC1918 IP address. In this case, bravetools can be initialised up with as multiple bridges without any DNS conflicts. I've tested this on linux and Mac and containers are created and networked without any issues.

There's a lot to be said for environment isolation that is allowed by your own bridge - therefore I'm wondering if we should leave this as is.

**Comment by Szubie** [comment]
> There's a lot to be said for environment isolation that is allowed by your own bridge - therefore I'm wondering if we should leave this as is.

Yes, that makes sense to me. Given that multiple bridges can work without issues it seems fine to create and use them.
