### ISSUE TITLE
Bravetools image naming schema

### ISSUE THREAD

**Issue by Szubie** [bravetools/bravetools#140]
At the moment Bravetools image definitions span several fields, and may possibly expand in future as bravetools moves towards multiple remotes. These fields are generally just concatenated together internally anyway to uniquely identify an image. It would be nice to allow the users to specify the image they want using just one field.

The `lxc` tool and LXD public image store already has a schema which we may want to emulate to better integrate with the existing ecosystem. It is also much briefer, which is nice. Here's the schema:

`[remote:]name[/version][/arch][/type]`

The public LXD image store hierarchical directories can be browsed [here](https://uk.lxd.images.canonical.com/images/). These public images are associated with the "images:" remote in the `lxc` tool.

**Comment by idroz** [comment]
Addressed in #164
