### ISSUE TITLE
Bravetools multiple remotes

### ISSUE THREAD

**Issue by Szubie** [bravetools/bravetools#141]
For the moment bravetools can only build/deploy to a single LXD instance, the local one that was set up during `brave init`. It would be very useful to be able to build images locally and deploy them into production using bravetools.

Bravetools recently switched remote backend to make preperations for this change. https://github.com/bravetools/bravetools/pull/125

To allow users to specify remotes during build/deploy time it may be good to add new fields to the bravefile. Alternatively, there is a suggestion here https://github.com/bravetools/bravetools/issues/140 to bake the remote info into the Bravefile "Image" field.

### Adding new remotes
There's also the question of how to allow users to add new remotes. For now, the user can manually add the required file to the ~/.bravetools/remotes directory and the corresponding server cert with matching filename to the ~/.bravetools/servercerts dir. They would then have to manually add their client keys to the remote LXD server manually (perhaps using SSH).

This works and is very secure, but we could add a CLI command that creates and authenticates the new remote automatically if a Trust Password or Token for the server is known (see [LXD docs for remote auth](https://linuxcontainers.org/lxd/docs/master/authentication/)).

Alternatively if the manaul workflow is encouraged we could provide documentation for it.

**Comment by idroz** [comment]
Addressed in #145
