### ISSUE TITLE
Device IP not within LXD bridge subnet

### ISSUE THREAD

**Issue by Szubie** [bravetools/bravetools#156]
Running current master branch (https://github.com/bravetools/bravetools/commit/2f44c394548a47190b941b9df53e611cfd5c3ece) on Ubuntu Linux, followed uninstall instructions and ran `brave init`

Attempting to deploy a unit to 10.0.0.5 results in an error - this used to work before.

Error message:
```sh
Device IP address "10.0.0.5" not within network "benjaminbr0" subnet
```

Output of `lxc network info benjaminbr0` show that the bridge IP is 10.131.219.1/24
Running `brave deploy --ip 10.131.219.10` works fine.

I see that there is an option to specify network bridge IP in `brave init` which I never used before - previously I relied on the bridge always being on 10.0.0.1. I suppose that going forwards I should now remember to set this option to the desired IP on brave init, to avoid having to adjust to the randomly selected bridge IP.

**Comment by idroz** [comment]
Yes - this is the "cost" of having a network bridge that doesn't clash with any existing networks.

We can make the warning more verbose e.g.

> static IPs must be provided in 10.131.219.* range

**Comment by Szubie** [comment]
Improved error messaging in https://github.com/bravetools/bravetools/pull/238
