### ISSUE TITLE
Deleting a unit with a mounted directory breaks multipass

### ISSUE THREAD

**Issue by idroz** [bravetools/bravetools#230]
Brave successfully deletes a unit with a mounted directory. However when attempting to mount another directory to it, multipass issues an error: 

```
mount failed: The following errors occurred:
"brave:/home/ubuntu/volumes/brave_8c97bb22fcb42426a7bb36d0d2d23381bf6f9afff7b3cd486e2307b4" is already mounted
```

**Comment by Szubie** [comment]
Addressed by https://github.com/bravetools/bravetools/pull/231
