### ISSUE TITLE
Setting LXC Params for access to /dev/net/tun0 on host

### ISSUE THREAD

**Issue by aob-lol** [bravetools/bravetools#248]
**Is your feature request related to a problem? Please describe.**
I am attempting to deploy an Ubuntu LTS (22.04) container which will use OpenVPN for network connections to a LXD baremetal server. My bravefile properly installs all packages and copies over my OpenVPN config. However, there is a permissions error on the container. The OpenVPN systemd unit I describe in my bravefile fails with a permissions error:

```
TUN Error: tun_tx_queue_len_error: Operation not permitted
EVENT: TUN_SETUP_FAILED [FATAL ERROR] tun_tx_queue_len_error: Operation not permitted
ERROR: TUN_SETUP_FAILED
EVENT: DISCONNECTED
```
I can see that the OpenVPN client is successfully negotiating with the remote VPN server, but the initialization fails after that.

I have also tried adding /dev/net as a device using the Brave CLI but I just can't get it to work.

**Describe the solution you'd like**
Common wisdom for solving this comes from the Proxmox community. Within Proxmox, one can set LXC container cgroups and permissions. In their world, adding the following to the LXC configuration file would open /dev/net/tun0 on the host:

```
lxc.cgroup.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir
```

In my ideal scenario, it would be possible to set these directives from a Bravefile, or even through use of the CLI. 

**Describe alternatives you've considered**
I'm currently running a Ubuntu VM with OpenVPN just fine on Proxmox, but I would love to be able to set this up using Bravetools.

**Additional context**
Thank you for your time and consideration!

**Comment by Szubie** [comment]
Bravetools uses LXD to manage containers - although LXD internally uses LXC as its container engine it isn't possible to directly use the above solution without changes. Before considering changes to Bravetools it would be best to investigate solving the issue with LXD directly first so we know what to fix.

/dev/net/tun is supposedly [created for LXD containers by default](https://documentation.ubuntu.com/lxd/en/stable-4.0/container-environment/#devices), but I noticed you mentioned /dev/net/tun0.

[This post](https://askubuntu.com/questions/650471/how-do-i-allow-dev-net-tun-in-a-lxd-managed-lxc-container/701624#701624) shows how to mount /dev/net/tun to your container using the LXD client:
```sh
lxc config device add CONTAINER tun unix-char path=/dev/net/tun
```
If you need /dev/net/tun0 to be mounted instead be sure to edit the command as needed.

If you still get permission issues, ensure the service is running as sudo. You could also temporarily set the container to run as privileged and restart it to see if that helps (although there are downsides to leaving it like that).

**Comment by aob-lol** [comment]
This is absolutely the answer, thank you! I was unsure where to turn for support and found myself here, and so I truly appreciate the help. With your guidance I got it working.

**Comment by Szubie** [comment]
Thanks for the update - glad we could solve the issue!

Might look into expanding the range of mount options bravetools supports to make it possible to do this without needing to use a separate tool.
