### ISSUE TITLE
Some images fail to publish on MacBook Pro (M1)

### ISSUE THREAD

**Issue by Szubie** [bravetools/bravetools#253]
After running `brave build` an error is encountered during the `Publishing` stage that prevents the image the being built.

The error message shown is:

```
failed to publish image: signal: broken pipe
```

This doesn't always happen - some images are built fine. But once it starts happening it seems to happen consistently.

**Environment:**
 - MacBook Pro (M1)
 - macOS Sonoma 14.2.1
 - Bravetools version: release-2.00
 - LXD version: 5.0.2

**Comment by idroz** [comment]
Does this happen when connected to a VPN?

**Comment by Szubie** [comment]
> Does this happen when connected to a VPN?

It happens whether I'm connected to a VPN or not - rebooting Multipass and the machine itself also does not make a difference.

**Comment by idroz** [comment]
I’ve had a similar issue when multipass resources were exhausted. Particularly ram/disk space, when packaging larger images. I’ve given it n-2 ram and 120gb disk. N is host ram.

**Comment by Szubie** [comment]
> I’ve had a similar issue when multipass resources were exhausted. Particularly ram/disk space, when packaging larger images. I’ve given it n-2 ram and 120gb disk. N is host ram.

Thanks, this was the issue. `multipass info` showed that I was out of disk space:
```
Disk usage:     11.0GiB out of 11.6GiB
```

This explains why building a new image derived from a previously built image with no changes failed - after allocating more disk space for Multipass there are no further issues.
