### ISSUE TITLE
Remove dependency on snap LXD

### ISSUE THREAD

**Issue by idroz** [bravetools/bravetools#257]
Bravetools seems to have enforced snap dependency on LXD. This needs to be a general lxd binary

https://github.com/bravetools/bravetools/issues/32#issuecomment-1949630775

**Comment by JayBusch** [comment]
I've attempted to address this here: https://github.com/bravetools/bravetools/pull/258

**Comment by idroz** [comment]
Fixed via #258 Thanks @JayBusch !
