### ISSUE TITLE
Brave init

### ISSUE THREAD

**Issue by esturniolo** [bravetools/bravetools#26]
Hi guys!
Thanks for sharing this spectacular tool. I hope that it can grow in the future.

I follow step by step the _Quick Tour_ in the Readme, but fails because it never mention the `brave init` command.

Once I ran it, the _Quick tour_ works like a charm.
Another thing is that we (users) don't know what `brave init` does and why we need to run this  first. Or how to remove that `brave init` does in the future, etc. Also I checked in the https://bravetools.github.io/ docs and you only mention it one time, explaining only this: _Create a new Bravetools host._
Can you add more info about `init`?

BTW, I think that the Readme is a little messy, because the _Quick Tour_ is in the first place, then the _Installation_ part and finally the _Command Reference_.
If you order it diferrently like:
- _Installation_
- _Command Reference_
- _Quick Tour_

Will be easy to follow the guides.

Thanks!!

EDIT: Even in the https://bravetools.github.io/bravetools/intro/quickstart/ you never mention the `brave init`.

**Comment by idroz** [comment]
Thanks! Agreed, `brave init` and docs in general definitely need some work. I'll get those changes sorted.

**Comment by esturniolo** [comment]
Thanks for your fast reponse.
I also missing the way to remove an image.
I created the _alpine-example-1.0_ image, but I can't remove it.
I didn't see nothing about this in `brave --help`

Sorry for mix topics here, but I see that is unnecesary to open a newissue for this.
If you want/need it, I can do it.

**Comment by idroz** [comment]
No worries.

To remove the image:

```
brave remove -i alpine-example-1.0
```

**Comment by idroz** [comment]
Hello again, I pushed several commits straight to master:

1. Added TOC and restructured README.md sections
2. Included Initialise Bravetools section with description of `brave init`
3. Updated CLI docs and quickstart in main Bravetools documentation to reflect requirement for `brave init`

Let me know if this clarifies the `brave init` story - thanks!

**Comment by esturniolo** [comment]
Hi!

This:

> brave init will:
> 
> Create ~/.bravetools directory that stores all your local images, configurations, and a live Unit database

And this:

> On Linux distributions:
> 
> Set up a new LXD profile brave
> Create a new LXD bridge bravebr0
> Create a new storage pool brave-TIMESTAMP
> These steps ensure that Bravetools establishes a connection with LXD server and runs a self-contained LXD environment that doesn't interfere with any potentially existing user profiles and LXD bridges.

... it's so much clearer. Thanks for this. Really.

By the other hand I read that you use this as VM for your needs. With LXD you must add as argument "VM" in somewhere (I can't remember the exact place).
If I want to use some Unit as a VM, the Unit is ready for that or in build time I must do something else?
And finally, once the Unit is up and running, is something like `docker exec -it blabla`?

Sorry for bother you with so much questions.

**Comment by idroz** [comment]
These are good questions and give us an insight into how bravetools is used outside our team!

## VM
We're using bravetools units in lieu of VMs. Multiple units are deployed on bare metal with ssh access enabled. Although LXD does have VM capability, we're not using VMs internally or in production since system containers fit our purposes better. I believe it's possible to export a unit as a VM image using `lxc image export imagename  --vm` and then import it through `lxc import` but haven't tried it.

## `docker exec` parallel
We've been debating this feature internally since early days. Right now the easiest thing to accomplish this is just thorugh lxc itself:

On Linux:
```
lxc exec UNITNAME sh
```

On Mac/Windows
```
multipass exec brave lxc exec UNITNAME sh
```

If there's a strong enough case for it, we'll implement it :smile:

**Comment by idroz** [comment]
By the way, are you happy for me to close the original issue? Any general questions, just open a new issue and we'll pick them up there.

**Comment by esturniolo** [comment]
> By the way, are you happy for me to close the original issue? 

Sure! No worries.

Everytime that you answer something I've got two or more newquestions. It's like an Hydra of questions!! :)
