### ISSUE TITLE
'brave base' command fails on Windows when exporting image

### ISSUE THREAD

**Issue by Szubie** [bravetools/bravetools#8]
**Describe the bug**
`brave base` command fails on Windows on final step, when exporting image.

**To Reproduce**
Run `brave base github.com/beringresearch/bravefiles/ubuntu/ubuntu-bionic-py3` on Windows.

After all dependencies are installed using apt, on the final step, the build will fail.

**Expected behavior**
Expected brave image to be built successfully.

**Command line log**
Publishing image ubuntu-bionic-py3
Exporting image ubuntu-bionic-py3
Failed to export image: remove ubuntu-bionic-py3-1.0.root: The process cannot access the file because it is being used by another process.

**Environment (please complete the following information):**
 - Your operating system name and version: Windows 10 Pro version 1903 (OS Build 18362.1082) 64-bit
 - Bravetools version: 1.53
 - LXD version: 4.4

**Comment by idroz** [comment]
This was merged in f172c8b and included in #16 

If issue persists, do reopen.
