### ISSUE TITLE
Cannot use bravetools with certain usernames

### ISSUE THREAD

**Issue by Szubie** [bravetools/bravetools#91]
Usernames that are too long or include special characters cause issues when using bravetools.

To reproduce, make a username longer than 12 characters. If using multipass, special characters cause issues when creating VM (including the underscore). Calling `brave init` will result in errors.

Environment:
- multipass 1.9.1+win
- Windows 10 Pro 19044.1706

I've made a pull request (https://github.com/bravetools/bravetools/pull/90) that attempts to address the issue by sanitizing the username. However, there are still a few issues that remain after the fix - there may be a better solution.

**Comment by idroz** [comment]
Addressed in #90
